/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    members: MemberAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    members: Member;
    media: Media;
    pages: Page;
    places: Place;
    'saved-places': SavedPlace;
    sessions: Session;
    accounts: Account;
    verifications: Verification;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    members: MembersSelect<false> | MembersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    places: PlacesSelect<false> | PlacesSelect<true>;
    'saved-places': SavedPlacesSelect<false> | SavedPlacesSelect<true>;
    sessions: SessionsSelect<false> | SessionsSelect<true>;
    accounts: AccountsSelect<false> | AccountsSelect<true>;
    verifications: VerificationsSelect<false> | VerificationsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
    'collection-query': CollectionQueryWidget;
    activity: ActivityWidget;
  };
  user: User | Member;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface MemberAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members".
 */
export interface Member {
  id: number;
  email: string;
  emailVerified?: boolean | null;
  name: string;
  image?: string | null;
  avatar?: (number | null) | Media;
  preferences?: {
    reducedMotion?: boolean | null;
    stepFreeDefault?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  collection: 'members';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  summary?: string | null;
  body?: string | null;
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "places".
 */
export interface Place {
  id: number;
  name: string;
  slug: string;
  kind: 'business' | 'culture' | 'historic' | 'outdoors' | 'public-art' | 'community';
  lifecycle: 'open' | 'temporarily_closed' | 'seasonal' | 'permanently_closed' | 'historical_only' | 'unknown';
  primaryCategory?: string | null;
  primaryArea?: string | null;
  logo?: (number | null) | Media;
  summary?: string | null;
  /**
   * @minItems 2
   * @maxItems 2
   */
  location?: [number, number] | null;
  address?: {
    formatted?: string | null;
    neighborhood?: string | null;
    postalCode?: string | null;
  };
  website?: string | null;
  phone?: string | null;
  /**
   * Restaurant/bar menus. Keep image galleries, PDFs, and official menu webpages as separate menu records.
   */
  menus?:
    | {
        label: string;
        format: 'image_gallery' | 'pdf' | 'web';
        mealPeriod?:
          | ('all_day' | 'breakfast' | 'brunch' | 'lunch' | 'dinner' | 'drinks' | 'dessert' | 'happy_hour' | 'seasonal')
          | null;
        language?: string | null;
        /**
         * Rights-cleared or venue-supplied menu images uploaded to Harlem Mights.
         */
        images?: (number | Media)[] | null;
        /**
         * Official remote menu images when we should not re-host the source file.
         */
        remoteImages?:
          | {
              url: string;
              alt?: string | null;
              sourceUrl?: string | null;
              id?: string | null;
            }[]
          | null;
        /**
         * Uploaded PDF copy when rights/persistence allow it.
         */
        pdf?: (number | null) | Media;
        /**
         * Official remote PDF or menu webpage URL. HTTPS strongly preferred.
         */
        url?: string | null;
        /**
         * Extra exact HTTPS origins the secure in-app browser may follow. The initial URL origin is always added automatically. No wildcards.
         */
        allowedOrigins?:
          | {
              origin: string;
              id?: string | null;
            }[]
          | null;
        sourceUrl?: string | null;
        lastVerifiedAt?: string | null;
        effectiveFrom?: string | null;
        effectiveUntil?: string | null;
        active?: boolean | null;
        id?: string | null;
      }[]
    | null;
  dataQuality?: {
    state?: ('unverified' | 'partially_verified' | 'verified' | 'needs_review') | null;
    lastReviewedAt?: string | null;
  };
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "saved-places".
 */
export interface SavedPlace {
  id: number;
  member: number | Member;
  place: number | Place;
  updatedAt: string;
  createdAt: string;
}
/**
 * Auto-generated from Better Auth schema (session)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sessions".
 */
export interface Session {
  id: number;
  expiresAt: string;
  token: string;
  ipAddress?: string | null;
  userAgent?: string | null;
  user: number | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * Auto-generated from Better Auth schema (account)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "accounts".
 */
export interface Account {
  id: number;
  accountId: string;
  providerId: string;
  user: number | User;
  accessToken?: string | null;
  refreshToken?: string | null;
  idToken?: string | null;
  accessTokenExpiresAt?: string | null;
  refreshTokenExpiresAt?: string | null;
  scope?: string | null;
  password?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Auto-generated from Better Auth schema (verification)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "verifications".
 */
export interface Verification {
  id: number;
  identifier: string;
  value: string;
  expiresAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'members';
        value: number | Member;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'places';
        value: number | Place;
      } | null)
    | ({
        relationTo: 'saved-places';
        value: number | SavedPlace;
      } | null)
    | ({
        relationTo: 'sessions';
        value: number | Session;
      } | null)
    | ({
        relationTo: 'accounts';
        value: number | Account;
      } | null)
    | ({
        relationTo: 'verifications';
        value: number | Verification;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'members';
        value: number | Member;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'members';
        value: number | Member;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members_select".
 */
export interface MembersSelect<T extends boolean = true> {
  email?: T;
  emailVerified?: T;
  name?: T;
  image?: T;
  avatar?: T;
  preferences?:
    | T
    | {
        reducedMotion?: T;
        stepFreeDefault?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  body?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "places_select".
 */
export interface PlacesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  kind?: T;
  lifecycle?: T;
  primaryCategory?: T;
  primaryArea?: T;
  logo?: T;
  summary?: T;
  location?: T;
  address?:
    | T
    | {
        formatted?: T;
        neighborhood?: T;
        postalCode?: T;
      };
  website?: T;
  phone?: T;
  menus?:
    | T
    | {
        label?: T;
        format?: T;
        mealPeriod?: T;
        language?: T;
        images?: T;
        remoteImages?:
          | T
          | {
              url?: T;
              alt?: T;
              sourceUrl?: T;
              id?: T;
            };
        pdf?: T;
        url?: T;
        allowedOrigins?:
          | T
          | {
              origin?: T;
              id?: T;
            };
        sourceUrl?: T;
        lastVerifiedAt?: T;
        effectiveFrom?: T;
        effectiveUntil?: T;
        active?: T;
        id?: T;
      };
  dataQuality?:
    | T
    | {
        state?: T;
        lastReviewedAt?: T;
      };
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "saved-places_select".
 */
export interface SavedPlacesSelect<T extends boolean = true> {
  member?: T;
  place?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sessions_select".
 */
export interface SessionsSelect<T extends boolean = true> {
  expiresAt?: T;
  token?: T;
  ipAddress?: T;
  userAgent?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "accounts_select".
 */
export interface AccountsSelect<T extends boolean = true> {
  accountId?: T;
  providerId?: T;
  user?: T;
  accessToken?: T;
  refreshToken?: T;
  idToken?: T;
  accessTokenExpiresAt?: T;
  refreshTokenExpiresAt?: T;
  scope?: T;
  password?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "verifications_select".
 */
export interface VerificationsSelect<T extends boolean = true> {
  identifier?: T;
  value?: T;
  expiresAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collection-query_widget".
 */
export interface CollectionQueryWidget {
  data?: {
    title?: string | null;
    relatedCollection:
      'users' | 'members' | 'media' | 'pages' | 'places' | 'saved-places' | 'sessions' | 'accounts' | 'verifications';
    where?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    sortField?: string | null;
    sortDirection?: ('asc' | 'desc') | null;
    limit?: number | null;
  };
  width: 'x-small' | 'small' | 'medium' | 'large' | 'x-large' | 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activity_widget".
 */
export interface ActivityWidget {
  data?: {
    excludedCollections?:
      | (
          | 'users'
          | 'members'
          | 'media'
          | 'pages'
          | 'places'
          | 'saved-places'
          | 'sessions'
          | 'accounts'
          | 'verifications'
        )[]
      | null;
  };
  width: 'x-small' | 'small' | 'medium' | 'large' | 'x-large' | 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}