/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    members: MemberAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    members: Member;
    media: Media;
    pages: Page;
    places: Place;
    'saved-places': SavedPlace;
    walks: Walk;
    stories: Story;
    events: Event;
    sessions: Session;
    accounts: Account;
    verifications: Verification;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
    'payload-llm-instructions': PayloadLlmInstruction;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    members: MembersSelect<false> | MembersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    places: PlacesSelect<false> | PlacesSelect<true>;
    'saved-places': SavedPlacesSelect<false> | SavedPlacesSelect<true>;
    walks: WalksSelect<false> | WalksSelect<true>;
    stories: StoriesSelect<false> | StoriesSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    sessions: SessionsSelect<false> | SessionsSelect<true>;
    accounts: AccountsSelect<false> | AccountsSelect<true>;
    verifications: VerificationsSelect<false> | VerificationsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
    'payload-llm-instructions': PayloadLlmInstructionsSelect<false> | PayloadLlmInstructionsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    welcome: WelcomeWidget;
    collections: CollectionsWidget;
    'collection-query': CollectionQueryWidget;
    activity: ActivityWidget;
    'upload-dropzone': UploadDropzoneWidget;
  };
  user: User | Member;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface MemberAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  createdBy?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'members';
        value: number | Member;
      } | null);
  updatedBy?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'members';
        value: number | Member;
      } | null);
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members".
 */
export interface Member {
  id: number;
  email: string;
  emailVerified?: boolean | null;
  name: string;
  image?: string | null;
  avatar?: (number | null) | Media;
  preferences?: {
    reducedMotion?: boolean | null;
    stepFreeDefault?: boolean | null;
  };
  createdBy?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'members';
        value: number | Member;
      } | null);
  updatedBy?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'members';
        value: number | Member;
      } | null);
  updatedAt: string;
  createdAt: string;
  collection: 'members';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  role?: ('hero' | 'gallery' | 'historical' | 'thumbnail' | 'map_pin') | null;
  source?:
    | (
        | 'commissioned'
        | 'nypl'
        | 'loc'
        | 'wikimedia_commons'
        | 'google_places'
        | 'unsplash'
        | 'pexels'
        | 'venue_supplied'
        | 'other'
      )
    | null;
  sourceUrl?: string | null;
  license?: string | null;
  licenseUrl?: string | null;
  creator?: string | null;
  credit?: string | null;
  attributionText?: string | null;
  /**
   * Capture date or era as stated by the source.
   */
  capturedAt?: string | null;
  ingestedAt?: string | null;
  placeholderHash?: string | null;
  dominantColor?: string | null;
  shareAlike?: boolean | null;
  noDerivatives?: boolean | null;
  createdBy?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'members';
        value: number | Member;
      } | null);
  updatedBy?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'members';
        value: number | Member;
      } | null);
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  original?: {
    filename?: string | null;
    url?: string | null;
    mimeType?: string | null;
    filesize?: number | null;
    width?: number | null;
    height?: number | null;
    prefix?: string | null;
    _objectKey?: string | null;
  };
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  summary?: string | null;
  body?: string | null;
  published?: boolean | null;
  createdBy?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'members';
        value: number | Member;
      } | null);
  updatedBy?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'members';
        value: number | Member;
      } | null);
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "places".
 */
export interface Place {
  id: number;
  name: string;
  slug: string;
  /**
   * Old generated public paths. These stay resolvable and redirect to the current name-led slug.
   */
  legacySlugs?:
    | {
        slug: string;
        id?: string | null;
      }[]
    | null;
  kind: 'business' | 'culture' | 'historic' | 'outdoors' | 'public-art' | 'community';
  lifecycle: 'open' | 'temporarily_closed' | 'seasonal' | 'permanently_closed' | 'historical_only' | 'unknown';
  primaryCategory?: string | null;
  primaryArea?: string | null;
  logo?: (number | null) | Media;
  /**
   * Editorial images. Each image must include a verified source, license, credit and attribution before it can render.
   */
  images?: (number | Media)[] | null;
  summary?: string | null;
  /**
   * @minItems 2
   * @maxItems 2
   */
  location?: [number, number] | null;
  locationAccuracy: 'verified' | 'approx' | 'pending';
  locationSource?: {
    /**
     * OSM node/way URL, survey note, or other source for the point.
     */
    url?: string | null;
    verifiedAt?: string | null;
  };
  entrance?: {
    /**
     * e.g. "Box office door, 253 W 125th St".
     */
    note?: string | null;
    /**
     * @minItems 2
     * @maxItems 2
     */
    location?: [number, number] | null;
    sourceUrl?: string | null;
    verifiedAt?: string | null;
  };
  address?: {
    formatted?: string | null;
    neighborhood?: string | null;
    postalCode?: string | null;
  };
  website?: string | null;
  phone?: string | null;
  /**
   * Hours as published by the source. `osm` holds the raw OpenStreetMap opening_hours value; never transcribe it by hand.
   */
  openingHours?: {
    /**
     * Raw opening_hours tag, e.g. "Mo-Fr 11:00-23:00; Sa 12:00-24:00".
     */
    osm?: string | null;
    /**
     * Human-readable hours when a source gives prose instead of a parseable value.
     */
    note?: string | null;
    sourceUrl?: string | null;
    verifiedAt?: string | null;
  };
  /**
   * Restaurant/bar menus. Keep image galleries, PDFs, and official menu webpages as separate menu records.
   */
  menus?:
    | {
        label: string;
        format: 'image_gallery' | 'pdf' | 'web';
        mealPeriod?:
          | ('all_day' | 'breakfast' | 'brunch' | 'lunch' | 'dinner' | 'drinks' | 'dessert' | 'happy_hour' | 'seasonal')
          | null;
        language?: string | null;
        /**
         * Rights-cleared or venue-supplied menu images uploaded to Harlem Might.
         */
        images?: (number | Media)[] | null;
        /**
         * Official remote menu images when we should not re-host the source file.
         */
        remoteImages?:
          | {
              url: string;
              alt?: string | null;
              sourceUrl?: string | null;
              id?: string | null;
            }[]
          | null;
        /**
         * Uploaded PDF copy when rights/persistence allow it.
         */
        pdf?: (number | null) | Media;
        /**
         * Official remote PDF or menu webpage URL. HTTPS strongly preferred.
         */
        url?: string | null;
        /**
         * Extra exact HTTPS origins the secure in-app browser may follow. The initial URL origin is always added automatically. No wildcards.
         */
        allowedOrigins?:
          | {
              origin: string;
              id?: string | null;
            }[]
          | null;
        sourceUrl?: string | null;
        lastVerifiedAt?: string | null;
        effectiveFrom?: string | null;
        effectiveUntil?: string | null;
        active?: boolean | null;
        id?: string | null;
      }[]
    | null;
  dataQuality?: {
    state?: ('unverified' | 'partially_verified' | 'verified' | 'needs_review') | null;
    lastReviewedAt?: string | null;
  };
  featured?: boolean | null;
  createdBy?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'members';
        value: number | Member;
      } | null);
  updatedBy?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'members';
        value: number | Member;
      } | null);
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "saved-places".
 */
export interface SavedPlace {
  id: number;
  member: number | Member;
  place: number | Place;
  createdBy?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'members';
        value: number | Member;
      } | null);
  updatedBy?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'members';
        value: number | Member;
      } | null);
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "walks".
 */
export interface Walk {
  id: number;
  title: string;
  /**
   * Lowercase words joined by hyphens. Used in the URL.
   */
  slug: string;
  /**
   * The premise: why walk this route, in two or three sentences.
   */
  summary: string;
  /**
   * In walking order. Each stop is a catalogue place; its facts live on the place record.
   */
  stops: {
    place: number | Place;
    /**
     * What to look at here, on this walk.
     */
    note?: string | null;
    id?: string | null;
  }[];
  /**
   * Cover and route images. Each image must include a verified source, license, credit and attribution before it can render.
   */
  images?: (number | Media)[] | null;
  distanceMeters: number;
  /**
   * Expected time at an easy pace, stops included.
   */
  durationMinutes: number;
  /**
   * Where to begin, e.g. a corner or station exit.
   */
  startDescription: string;
  endDescription: string;
  /**
   * Leave empty unless you have a source. Never write "accessible" on its own.
   */
  accessibility?: {
    note?: string | null;
    sourceUrl?: string | null;
    verifiedAt?: string | null;
  };
  /**
   * Where the facts on this record come from. Name the source and link it.
   */
  sources?:
    | {
        label: string;
        url?: string | null;
        /**
         * When the source was last read.
         */
        accessedAt?: string | null;
        id?: string | null;
      }[]
    | null;
  createdBy?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'members';
        value: number | Member;
      } | null);
  updatedBy?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'members';
        value: number | Member;
      } | null);
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stories".
 */
export interface Story {
  id: number;
  title: string;
  /**
   * Lowercase words joined by hyphens. Used in the URL.
   */
  slug: string;
  /**
   * One or two sentences under the headline.
   */
  dek?: string | null;
  body: string;
  /**
   * Every place this story is about. Each place page links back.
   */
  places?: (number | Place)[] | null;
  /**
   * Lead and inline images. Each image must include a verified source, license, credit and attribution before it can render.
   */
  images?: (number | Media)[] | null;
  /**
   * Archival or commissioned images. Every item needs a credit and a rights basis.
   */
  archive?:
    | {
        media: number | Media;
        caption?: string | null;
        credit: string;
        rights: 'owned' | 'licensed' | 'venue_supplied' | 'open_license' | 'public_domain';
        rightsHolder?: string | null;
        /**
         * e.g. CC BY 4.0, with version.
         */
        license?: string | null;
        sourceUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Where the facts on this record come from. Name the source and link it.
   */
  sources?:
    | {
        label: string;
        url?: string | null;
        /**
         * When the source was last read.
         */
        accessedAt?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Byline as printed.
   */
  author: string;
  /**
   * Curator accountable for corrections.
   */
  editorialOwner?: (number | null) | User;
  publishedAt?: string | null;
  createdBy?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'members';
        value: number | Member;
      } | null);
  updatedBy?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'members';
        value: number | Member;
      } | null);
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  /**
   * Lowercase words joined by hyphens. Used in the URL.
   */
  slug: string;
  startsAt: string;
  startsAt_tz: 'America/New_York';
  endsAt: string;
  endsAt_tz: 'America/New_York';
  lifecycle: 'scheduled' | 'cancelled' | 'postponed';
  place?: (number | null) | Place;
  /**
   * Event art and venue images. Each image must include a verified source, license, credit and attribution before it can render.
   */
  images?: (number | Media)[] | null;
  venueName?: string | null;
  venueUrl?: string | null;
  /**
   * The listing this event was copied from (usually the venue page).
   */
  sourceUrl: string;
  /**
   * When the listing was first read.
   */
  fetchedAt: string;
  /**
   * When someone last checked the listing still says this.
   */
  lastVerifiedAt: string;
  ticketUrl?: string | null;
  createdBy?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'members';
        value: number | Member;
      } | null);
  updatedBy?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'members';
        value: number | Member;
      } | null);
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Auto-generated from Better Auth schema (session)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sessions".
 */
export interface Session {
  id: number;
  expiresAt: string;
  token: string;
  ipAddress?: string | null;
  userAgent?: string | null;
  user: number | User;
  createdBy?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'members';
        value: number | Member;
      } | null);
  updatedBy?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'members';
        value: number | Member;
      } | null);
  updatedAt: string;
  createdAt: string;
}
/**
 * Auto-generated from Better Auth schema (account)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "accounts".
 */
export interface Account {
  id: number;
  accountId: string;
  providerId: string;
  user: number | User;
  accessToken?: string | null;
  refreshToken?: string | null;
  idToken?: string | null;
  accessTokenExpiresAt?: string | null;
  refreshTokenExpiresAt?: string | null;
  scope?: string | null;
  password?: string | null;
  createdBy?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'members';
        value: number | Member;
      } | null);
  updatedBy?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'members';
        value: number | Member;
      } | null);
  updatedAt: string;
  createdAt: string;
}
/**
 * Auto-generated from Better Auth schema (verification)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "verifications".
 */
export interface Verification {
  id: number;
  identifier: string;
  value: string;
  expiresAt: string;
  createdBy?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'members';
        value: number | Member;
      } | null);
  updatedBy?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'members';
        value: number | Member;
      } | null);
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'members';
        value: number | Member;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'places';
        value: number | Place;
      } | null)
    | ({
        relationTo: 'saved-places';
        value: number | SavedPlace;
      } | null)
    | ({
        relationTo: 'walks';
        value: number | Walk;
      } | null)
    | ({
        relationTo: 'stories';
        value: number | Story;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'sessions';
        value: number | Session;
      } | null)
    | ({
        relationTo: 'accounts';
        value: number | Account;
      } | null)
    | ({
        relationTo: 'verifications';
        value: number | Verification;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'members';
        value: number | Member;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'members';
        value: number | Member;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-llm-instructions".
 */
export interface PayloadLlmInstruction {
  id: string;
  entitySlug: string;
  title?: string | null;
  entityType: 'collection' | 'global';
  additionalInstructions?: string | null;
  systemInstructions?: string | null;
  createdBy?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'members';
        value: number | Member;
      } | null);
  updatedBy?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'members';
        value: number | Member;
      } | null);
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  createdBy?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members_select".
 */
export interface MembersSelect<T extends boolean = true> {
  email?: T;
  emailVerified?: T;
  name?: T;
  image?: T;
  avatar?: T;
  preferences?:
    | T
    | {
        reducedMotion?: T;
        stepFreeDefault?: T;
      };
  createdBy?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  role?: T;
  source?: T;
  sourceUrl?: T;
  license?: T;
  licenseUrl?: T;
  creator?: T;
  credit?: T;
  attributionText?: T;
  capturedAt?: T;
  ingestedAt?: T;
  placeholderHash?: T;
  dominantColor?: T;
  shareAlike?: T;
  noDerivatives?: T;
  createdBy?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  original?:
    | T
    | {
        filename?: T;
        url?: T;
        mimeType?: T;
        filesize?: T;
        width?: T;
        height?: T;
        prefix?: T;
        _objectKey?: T;
      };
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  body?: T;
  published?: T;
  createdBy?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "places_select".
 */
export interface PlacesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  legacySlugs?:
    | T
    | {
        slug?: T;
        id?: T;
      };
  kind?: T;
  lifecycle?: T;
  primaryCategory?: T;
  primaryArea?: T;
  logo?: T;
  images?: T;
  summary?: T;
  location?: T;
  locationAccuracy?: T;
  locationSource?:
    | T
    | {
        url?: T;
        verifiedAt?: T;
      };
  entrance?:
    | T
    | {
        note?: T;
        location?: T;
        sourceUrl?: T;
        verifiedAt?: T;
      };
  address?:
    | T
    | {
        formatted?: T;
        neighborhood?: T;
        postalCode?: T;
      };
  website?: T;
  phone?: T;
  openingHours?:
    | T
    | {
        osm?: T;
        note?: T;
        sourceUrl?: T;
        verifiedAt?: T;
      };
  menus?:
    | T
    | {
        label?: T;
        format?: T;
        mealPeriod?: T;
        language?: T;
        images?: T;
        remoteImages?:
          | T
          | {
              url?: T;
              alt?: T;
              sourceUrl?: T;
              id?: T;
            };
        pdf?: T;
        url?: T;
        allowedOrigins?:
          | T
          | {
              origin?: T;
              id?: T;
            };
        sourceUrl?: T;
        lastVerifiedAt?: T;
        effectiveFrom?: T;
        effectiveUntil?: T;
        active?: T;
        id?: T;
      };
  dataQuality?:
    | T
    | {
        state?: T;
        lastReviewedAt?: T;
      };
  featured?: T;
  createdBy?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "saved-places_select".
 */
export interface SavedPlacesSelect<T extends boolean = true> {
  member?: T;
  place?: T;
  createdBy?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "walks_select".
 */
export interface WalksSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  stops?:
    | T
    | {
        place?: T;
        note?: T;
        id?: T;
      };
  images?: T;
  distanceMeters?: T;
  durationMinutes?: T;
  startDescription?: T;
  endDescription?: T;
  accessibility?:
    | T
    | {
        note?: T;
        sourceUrl?: T;
        verifiedAt?: T;
      };
  sources?:
    | T
    | {
        label?: T;
        url?: T;
        accessedAt?: T;
        id?: T;
      };
  createdBy?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stories_select".
 */
export interface StoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  dek?: T;
  body?: T;
  places?: T;
  images?: T;
  archive?:
    | T
    | {
        media?: T;
        caption?: T;
        credit?: T;
        rights?: T;
        rightsHolder?: T;
        license?: T;
        sourceUrl?: T;
        id?: T;
      };
  sources?:
    | T
    | {
        label?: T;
        url?: T;
        accessedAt?: T;
        id?: T;
      };
  author?: T;
  editorialOwner?: T;
  publishedAt?: T;
  createdBy?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  startsAt?: T;
  startsAt_tz?: T;
  endsAt?: T;
  endsAt_tz?: T;
  lifecycle?: T;
  place?: T;
  images?: T;
  venueName?: T;
  venueUrl?: T;
  sourceUrl?: T;
  fetchedAt?: T;
  lastVerifiedAt?: T;
  ticketUrl?: T;
  createdBy?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sessions_select".
 */
export interface SessionsSelect<T extends boolean = true> {
  expiresAt?: T;
  token?: T;
  ipAddress?: T;
  userAgent?: T;
  user?: T;
  createdBy?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "accounts_select".
 */
export interface AccountsSelect<T extends boolean = true> {
  accountId?: T;
  providerId?: T;
  user?: T;
  accessToken?: T;
  refreshToken?: T;
  idToken?: T;
  accessTokenExpiresAt?: T;
  refreshTokenExpiresAt?: T;
  scope?: T;
  password?: T;
  createdBy?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "verifications_select".
 */
export interface VerificationsSelect<T extends boolean = true> {
  identifier?: T;
  value?: T;
  expiresAt?: T;
  createdBy?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-llm-instructions_select".
 */
export interface PayloadLlmInstructionsSelect<T extends boolean = true> {
  id?: T;
  entitySlug?: T;
  title?: T;
  entityType?: T;
  additionalInstructions?: T;
  systemInstructions?: T;
  createdBy?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "welcome_widget".
 */
export interface WelcomeWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collection-query_widget".
 */
export interface CollectionQueryWidget {
  data?: {
    title?: string | null;
    relatedCollection:
      | 'users'
      | 'members'
      | 'media'
      | 'pages'
      | 'places'
      | 'saved-places'
      | 'walks'
      | 'stories'
      | 'events'
      | 'sessions'
      | 'accounts'
      | 'verifications';
    where?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    sortField?: string | null;
    sortDirection?: ('asc' | 'desc') | null;
    limit?: number | null;
  };
  width: 'x-small' | 'small' | 'medium' | 'large' | 'x-large' | 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activity_widget".
 */
export interface ActivityWidget {
  data?: {
    excludedCollections?:
      | (
          | 'users'
          | 'members'
          | 'media'
          | 'pages'
          | 'places'
          | 'saved-places'
          | 'walks'
          | 'stories'
          | 'events'
          | 'sessions'
          | 'accounts'
          | 'verifications'
        )[]
      | null;
  };
  width: 'small' | 'medium' | 'large' | 'x-large' | 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "upload-dropzone_widget".
 */
export interface UploadDropzoneWidget {
  data?: {
    excludedCollections?: 'media'[] | null;
  };
  width: 'x-small' | 'small' | 'medium' | 'large' | 'x-large' | 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}