// Generated by @viro-external/specs bake-rive-native from harlem-courts.tsx. Do not edit;
// rerun `pnpm specs:bake-rive-native` after changing a Rive file.
import type { RiveBaked } from "@viro-external/ui";

export const RIVE_BAKES: Record<string, RiveBaked> = {
  "platform-lab-lesson": {
    aspect: 1.6,
    clips: {
      "Loading": { source: require("./platform-lab-lesson/Loading.gif"), loop: true, durationMs: 2000 },
      "Entering": { source: require("./platform-lab-lesson/Entering.gif"), loop: false, durationMs: 720 },
      "Idle": { source: require("./platform-lab-lesson/Idle.gif"), loop: false, durationMs: 40 },
      "Submitting": { source: require("./platform-lab-lesson/Submitting.gif"), loop: true, durationMs: 1200 },
      "Correct": { source: require("./platform-lab-lesson/Correct.gif"), loop: false, durationMs: 320 },
    },
    play: "Loading",
    next: {"Entering":"Idle","Correct":"Idle"},
    onSelect: {"Loading":"Entering","Submitting":"Correct"},
    buttons: [{"id":"0","label":"0","rect":[0.640625,0.1,0.328125,0.105]},{"id":"1","label":"1","rect":[0.640625,0.215,0.328125,0.105]},{"id":"2","label":"2","rect":[0.640625,0.33,0.328125,0.105]},{"id":"3","label":"3","rect":[0.640625,0.445,0.328125,0.105]},{"id":"4","label":"4","rect":[0.640625,0.56,0.328125,0.105]},{"id":"5","label":"5","rect":[0.640625,0.675,0.328125,0.105]},{"id":"listen","label":"Listen","rect":[0.0375,0.945,0.084375,0.0425]},{"id":"hint","label":"Hint","rect":[0.13125,0.945,0.084375,0.0425]},{"id":"board","label":"Board","rect":[0.225,0.945,0.084375,0.0425],"play":"Loading"},{"id":"retry","label":"Retry","rect":[0.31875,0.945,0.084375,0.0425],"play":"Entering"},{"id":"skip","label":"Skip","rect":[0.6390625,0.945,0.084375,0.0425]},{"id":"submit","label":"Submit","rect":[0.7328125,0.945,0.1171875,0.0425],"play":"Submitting"},{"id":"next","label":"Next","rect":[0.859375,0.945,0.109375,0.0425]}],
  },
};
