#!/usr/bin/env node
// One command from a clean checkout to Harlem Might on a Meta Quest:
//
//   pnpm --filter mobile quest              build and check the questDebug APK
//   pnpm --filter mobile quest --install    also install, start Metro, launch
//   pnpm --filter mobile quest --serial X   pick one of several adb devices
//
// android/ is not checked in. Every run regenerates it with
// `expo prebuild --clean` (CNG), the way the expo-pico example works, so the
// native project always equals what the config plugins produce.
//
// Each step prints one line. A failure prints the exact fix and exits 1; the
// full output of long steps goes to a log file named in the failure line.

import { spawn, spawnSync } from 'node:child_process';
import { createWriteStream, existsSync, mkdirSync, openSync, readdirSync, statSync } from 'node:fs';
import { tmpdir, homedir } from 'node:os';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  DEEP_LINK,
  PACKAGE_NAME,
  REQUIRED_NODE,
  checkQuestManifest,
  chooseMetroPort,
  isRequiredNode,
  newestBuildTools,
  parseAdbDevices,
  parseArgs,
  pickDevice,
  METRO_PORTS,
} from './quest-lib.mjs';

const appDir = join(dirname(fileURLToPath(import.meta.url)), '..');
const repoRoot = join(appDir, '../..');
const androidDir = join(appDir, 'android');
const apkPath = join(androidDir, 'app/build/outputs/apk/quest/debug/app-quest-debug.apk');
const logDir = join(tmpdir(), 'harlem-might-quest');
mkdirSync(logDir, { recursive: true });

let stepNumber = 0;
const ok = (message) => {
  stepNumber += 1;
  console.log(`[quest] ${stepNumber}. ok   ${message}`);
};
const fail = (message, fix) => {
  stepNumber += 1;
  console.error(`[quest] ${stepNumber}. FAIL ${message}`);
  if (fix) console.error(`[quest]    fix: ${fix}`);
  process.exit(1);
};

/** Runs a command with output to a log file. Resolves to the real exit code. */
const runLogged = (name, command, args, options = {}) =>
  new Promise((resolve) => {
    const logPath = join(logDir, `${name}.log`);
    const log = createWriteStream(logPath);
    const child = spawn(command, args, { stdio: ['ignore', 'pipe', 'pipe'], ...options });
    child.stdout.pipe(log, { end: false });
    child.stderr.pipe(log, { end: false });
    child.on('error', (error) => {
      log.end(`\n${error.message}\n`);
      resolve({ code: 127, logPath });
    });
    child.on('close', (code) => log.end(() => resolve({ code: code ?? 1, logPath })));
  });

const capture = (command, args, options = {}) =>
  spawnSync(command, args, { encoding: 'utf8', ...options });

const tailOf = (logPath, lines = 25) =>
  capture('tail', ['-n', String(lines), logPath]).stdout.trimEnd();

// --- arguments -------------------------------------------------------------

let args;
try {
  args = parseArgs(process.argv.slice(2));
} catch (error) {
  fail(error.message, 'pnpm --filter mobile quest [--install] [--serial <adb serial>]');
}
if (args.help) {
  console.log('usage: pnpm --filter mobile quest [--install] [--serial <adb serial>]');
  process.exit(0);
}

// --- 1. toolchain ----------------------------------------------------------

if (!isRequiredNode(process.versions.node)) {
  fail(
    `Node ${process.versions.node}; this repo pins ${REQUIRED_NODE} (.nvmrc)`,
    'nvm install && nvm use   (or: fnm use --install-if-missing), then rerun',
  );
}
{
  const result = capture(process.execPath, [join(appDir, 'scripts/assert-viro-fork.mjs')], { cwd: appDir });
  if (result.status !== 0) {
    console.error(result.stderr.trim() || result.stdout.trim());
    fail('Viro fork / Nitro Rive check', 'apply the change printed above, run `pnpm install`, then rerun');
  }
  const nitro = result.stdout.includes('Nitro Rive GPU bridge verified')
    ? 'Nitro Rive bridge present'
    : 'Nitro Rive bridge not installed (Rive/GPU panels would throw on mount)';
  ok(`Node ${process.versions.node}, Viro fork present, ${nitro}`);
}

// --- 2. CNG: regenerate android/ -------------------------------------------

{
  const { code, logPath } = await runLogged(
    'prebuild',
    'npx',
    ['expo', 'prebuild', '--clean', '--platform', 'android', '--no-install'],
    { cwd: appDir, env: { ...process.env, CI: '1', EXPO_NO_GIT_STATUS: '1' } },
  );
  if (code !== 0) {
    console.error(tailOf(logPath));
    fail(`expo prebuild --clean exited ${code} (log: ${logPath})`, 'fix the config plugin error above in app.config.ts or the plugin package, then rerun');
  }
  ok('android/ regenerated by expo prebuild --clean');
}

{
  const result = capture(
    process.execPath,
    ['--disable-warning=MODULE_TYPELESS_PACKAGE_JSON', join(repoRoot, 'tooling/verify-spatial-android.mjs'), '--require-android'],
    { cwd: repoRoot },
  );
  if (result.status !== 0) {
    console.error((result.stderr || result.stdout).trim());
    fail('generated android/ is missing a Quest/PICO contract entry', 'the plugin that owns the entry above stopped writing it; fix its options in app.config.ts');
  }
  ok('generated android/ matches the spatial contract');
}

// --- 3. Gradle -------------------------------------------------------------

{
  const started = Date.now();
  const { code, logPath } = await runLogged('gradle', './gradlew', [':app:assembleQuestDebug', '--no-daemon'], { cwd: androidDir });
  if (code !== 0) {
    console.error(tailOf(logPath, 40));
    fail(`gradle :app:assembleQuestDebug exited ${code} (log: ${logPath})`, 'read the first "What went wrong" block in the log; android/ is generated, so fix the plugin or dependency, not the file');
  }
  if (!existsSync(apkPath) || statSync(apkPath).mtimeMs < started) {
    fail(`gradle exited 0 but ${apkPath} was not rewritten`, 'rerun; if it repeats, delete android/app/build and rerun');
  }
  const seconds = Math.round((Date.now() - started) / 1000);
  ok(`assembleQuestDebug built ${apkPath.replace(`${appDir}/`, '')} in ${seconds}s`);
}

// --- 4. APK manifest -------------------------------------------------------

{
  const sdk = process.env.ANDROID_HOME || process.env.ANDROID_SDK_ROOT || join(homedir(), 'Library/Android/sdk');
  const buildToolsDir = join(sdk, 'build-tools');
  const newest = existsSync(buildToolsDir) ? newestBuildTools(readdirSync(buildToolsDir)) : undefined;
  if (!newest) fail(`no build-tools under ${buildToolsDir}`, 'set ANDROID_HOME to your SDK, or install build-tools with `sdkmanager "build-tools;36.0.0"`');
  const aapt2 = join(buildToolsDir, newest, 'aapt2');
  const dump = capture(aapt2, ['dump', 'xmltree', '--file', 'AndroidManifest.xml', apkPath]);
  if (dump.status !== 0) fail(`aapt2 (${newest}) could not read the APK: ${dump.stderr.trim()}`, `reinstall build-tools ${newest}`);
  const result = checkQuestManifest(dump.stdout);
  if (result.leaks.length) {
    console.error(result.leaks.map((line) => `  ${line}`).join('\n'));
    fail(`${result.leaks.length} PICO entries in the Quest manifest`, 'a PICO plugin wrote into src/main or src/quest; it must write only app/src/pico/AndroidManifest.xml');
  }
  if (!result.hasVolumetric) {
    fail('MANAGE_APP_VOLUMETRIC_WINDOWS missing from the Quest manifest', 'keep metaLayoutSdk: true in the @expo-pico/core options in app.config.ts');
  }
  ok(`aapt2 ${newest}: 0 pico/pvr entries, MANAGE_APP_VOLUMETRIC_WINDOWS present`);
}

if (!args.install) {
  console.log('[quest] done. To put it on a headset: pnpm --filter mobile quest --install');
  process.exit(0);
}

// --- 5. install and launch -------------------------------------------------

const devices = capture('adb', ['devices']);
if (devices.error) fail('adb not found', 'add $ANDROID_HOME/platform-tools to PATH');
const picked = pickDevice(parseAdbDevices(devices.stdout), args.serial);
if (picked.error) fail('device selection', picked.error);
const adb = (...rest) => capture('adb', ['-s', picked.serial, ...rest]);

{
  // Only this app's package is removed; nothing else on the headset is touched.
  const installed = adb('shell', 'pm', 'list', 'packages', PACKAGE_NAME).stdout
    .split('\n')
    .some((line) => line.trim() === `package:${PACKAGE_NAME}`);
  if (installed) {
    const removed = adb('uninstall', PACKAGE_NAME);
    if (removed.status !== 0) fail(`adb uninstall ${PACKAGE_NAME}: ${removed.stdout.trim()} ${removed.stderr.trim()}`, `adb -s ${picked.serial} uninstall ${PACKAGE_NAME}, then rerun`);
  }
  const install = adb('install', apkPath);
  if (install.status !== 0) fail(`adb install: ${install.stdout.trim()} ${install.stderr.trim()}`, 'wake the headset, keep it connected, then rerun with --install');
  ok(`installed on ${picked.serial}${installed ? ' (old build uninstalled first)' : ''}`);
}

const listenerCwd = (port) => {
  const pid = capture('lsof', ['-nP', `-iTCP:${port}`, '-sTCP:LISTEN', '-t']).stdout.trim().split('\n')[0];
  if (!pid) return undefined;
  const cwd = capture('lsof', ['-a', '-p', pid, '-d', 'cwd', '-Fn']).stdout
    .split('\n')
    .find((line) => line.startsWith('n'));
  return cwd ? cwd.slice(1) : '?';
};

const metroStatus = async (port) => {
  try {
    const response = await fetch(`http://127.0.0.1:${port}/status`, { signal: AbortSignal.timeout(2000) });
    return (await response.text()).includes('packager-status:running');
  } catch {
    return false;
  }
};

let metroPort;
{
  const owners = new Map();
  for (const port of METRO_PORTS) {
    const cwd = listenerCwd(port);
    if (cwd !== undefined) owners.set(port, cwd);
  }
  const choice = chooseMetroPort(owners, appDir);
  if (!choice) fail(`ports ${METRO_PORTS[0]}-${METRO_PORTS.at(-1)} are all taken`, 'stop a Metro you no longer need, then rerun');
  metroPort = choice.port;
  if (choice.reuse && (await metroStatus(metroPort))) {
    ok(`reusing this app's Metro on :${metroPort}`);
  } else {
    const logPath = join(logDir, 'metro.log');
    const out = openSync(logPath, 'a');
    const child = spawn('npx', ['expo', 'start', '--port', String(metroPort)], {
      cwd: appDir,
      detached: true,
      stdio: ['ignore', out, out],
      env: { ...process.env, CI: '1', EXPO_UNSTABLE_MCP_SERVER: '1' },
    });
    child.unref();
    const deadline = Date.now() + 120_000;
    while (!(await metroStatus(metroPort))) {
      if (Date.now() > deadline) fail(`Metro did not answer on :${metroPort} within 120s (log: ${logPath})`, `read ${logPath}; stop it with \`kill ${child.pid}\``);
      await new Promise((resolve) => setTimeout(resolve, 1000));
    }
    const skipped = [...owners.entries()].filter(([port]) => port < metroPort).map(([port, cwd]) => `:${port} (${cwd})`);
    ok(`Metro started on :${metroPort} (pid ${child.pid}, log ${logPath})${skipped.length ? `; skipped ${skipped.join(', ')}` : ''}`);
  }
}

{
  const reverse = adb('reverse', 'tcp:8081', `tcp:${metroPort}`);
  if (reverse.status !== 0) fail(`adb reverse: ${reverse.stderr.trim()}`, `adb -s ${picked.serial} reverse tcp:8081 tcp:${metroPort}`);
  const launch = adb('shell', 'am', 'start', '-a', 'android.intent.action.VIEW', '-d', DEEP_LINK, PACKAGE_NAME);
  if (launch.status !== 0 || /Error/.test(launch.stdout + launch.stderr)) {
    fail(`launch ${DEEP_LINK}: ${(launch.stdout + launch.stderr).trim()}`, `put the headset on (it must be awake), then: adb -s ${picked.serial} shell am start -a android.intent.action.VIEW -d ${DEEP_LINK} ${PACKAGE_NAME}`);
  }
  ok(`adb reverse tcp:8081 -> :${metroPort}; launched ${DEEP_LINK}`);
}
