/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ArRouteImport } from './routes/ar'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as StoriesRouteImport } from './routes/stories'
import { Route as TodayRouteImport } from './routes/today'
import { Route as WalksRouteImport } from './routes/walks'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminBusinessesRouteImport } from './routes/admin/businesses'
import { Route as PagesIndexRouteImport } from './routes/pages/index'
import { Route as PagesSlugRouteImport } from './routes/pages/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ArRoute = ArRouteImport.update({
  id: '/ar',
  path: '/ar',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesRoute = StoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const TodayRoute = TodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => rootRouteImport,
} as any)
const WalksRoute = WalksRouteImport.update({
  id: '/walks',
  path: '/walks',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBusinessesRoute = AdminBusinessesRouteImport.update({
  id: '/admin/businesses',
  path: '/admin/businesses',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesIndexRoute = PagesIndexRouteImport.update({
  id: '/pages/',
  path: '/pages/',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesSlugRoute = PagesSlugRouteImport.update({
  id: '/pages/$slug',
  path: '/pages/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ar': typeof ArRoute
  '/explore': typeof ExploreRoute
  '/profile': typeof ProfileRoute
  '/stories': typeof StoriesRoute
  '/today': typeof TodayRoute
  '/walks': typeof WalksRoute
  '/admin/businesses': typeof AdminBusinessesRoute
  '/pages/$slug': typeof PagesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/pages/': typeof PagesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ar': typeof ArRoute
  '/explore': typeof ExploreRoute
  '/profile': typeof ProfileRoute
  '/stories': typeof StoriesRoute
  '/today': typeof TodayRoute
  '/walks': typeof WalksRoute
  '/admin/businesses': typeof AdminBusinessesRoute
  '/pages/$slug': typeof PagesSlugRoute
  '/admin': typeof AdminIndexRoute
  '/pages': typeof PagesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ar': typeof ArRoute
  '/explore': typeof ExploreRoute
  '/profile': typeof ProfileRoute
  '/stories': typeof StoriesRoute
  '/today': typeof TodayRoute
  '/walks': typeof WalksRoute
  '/admin/businesses': typeof AdminBusinessesRoute
  '/pages/$slug': typeof PagesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/pages/': typeof PagesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ar'
    | '/explore'
    | '/profile'
    | '/stories'
    | '/today'
    | '/walks'
    | '/admin/businesses'
    | '/pages/$slug'
    | '/admin/'
    | '/pages/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ar'
    | '/explore'
    | '/profile'
    | '/stories'
    | '/today'
    | '/walks'
    | '/admin/businesses'
    | '/pages/$slug'
    | '/admin'
    | '/pages'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/ar'
    | '/explore'
    | '/profile'
    | '/stories'
    | '/today'
    | '/walks'
    | '/admin/businesses'
    | '/pages/$slug'
    | '/admin/'
    | '/pages/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ArRoute: typeof ArRoute
  ExploreRoute: typeof ExploreRoute
  ProfileRoute: typeof ProfileRoute
  StoriesRoute: typeof StoriesRoute
  TodayRoute: typeof TodayRoute
  WalksRoute: typeof WalksRoute
  AdminBusinessesRoute: typeof AdminBusinessesRoute
  PagesSlugRoute: typeof PagesSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  PagesIndexRoute: typeof PagesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ar': {
      id: '/ar'
      path: '/ar'
      fullPath: '/ar'
      preLoaderRoute: typeof ArRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories': {
      id: '/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/today': {
      id: '/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof TodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/walks': {
      id: '/walks'
      path: '/walks'
      fullPath: '/walks'
      preLoaderRoute: typeof WalksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/businesses': {
      id: '/admin/businesses'
      path: '/admin/businesses'
      fullPath: '/admin/businesses'
      preLoaderRoute: typeof AdminBusinessesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/': {
      id: '/pages/'
      path: '/pages'
      fullPath: '/pages/'
      preLoaderRoute: typeof PagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/$slug': {
      id: '/pages/$slug'
      path: '/pages/$slug'
      fullPath: '/pages/$slug'
      preLoaderRoute: typeof PagesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ArRoute: ArRoute,
  ExploreRoute: ExploreRoute,
  ProfileRoute: ProfileRoute,
  StoriesRoute: StoriesRoute,
  TodayRoute: TodayRoute,
  WalksRoute: WalksRoute,
  AdminBusinessesRoute: AdminBusinessesRoute,
  PagesSlugRoute: PagesSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  PagesIndexRoute: PagesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
